### ISSUE TITLE
Project Lead Requirements for mozsprint

### ISSUE THREAD

**Issue by garciajnatalie** [jeffreykeefer/Parkology#2]
**Tasks for Project Leads @garciajnatalie @jeffreykeefer**

## Note to the Project Lead :tada:
Congrats, @jeffreykeefer! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  - new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead-guide/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [x] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

**Comment by jeffreykeefer** [comment]
done
