### ISSUE TITLE
Checklist for featured projects

### ISSUE THREAD

**Issue by garciajnatalie** [jeffreykeefer/Parkology#3]
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/).

* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [ ] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] [Fill out this form](https://www.mozillapulse.org/add) to submit your project to Mozilla Pulse. Add the tags `mozsprint` and `2018`.

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready to be featured on Mozilla Pulse`. Your wrangler will review this issue and approve your project if everything looks good :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/). We're here to help you through this process.
